Upgrade headapps to JSS 22.3.1
sitecorelabs/xmcloud-foundation-head-dev pull request #190
Opened 2024-12-09 18:22 UTC by addy-pathania

JSS upgrade 22.3.1
For more info please refer: https://github.com/Sitecore/jss/releases/tag/v22.3.1

2024-12-09 21:08 UTC, art-alexeyenko requested changes
Looks good, some small comments around the containers part.
Did you check with Yavor on whether the container changes are actual and should be in?

2024-12-09 21:31 UTC, addy-pathania commented on local-containers/scripts/up.ps1
> +#set node version
why? its still setting the node version to the env

2024-12-09 21:35 UTC, addy-pathania commented
> Looks good, some small comments around the containers part. Did you check with Yavor on whether the container changes are actual and should be in?

Yes I did and he said they are good to go.
cc @yavorsk

2024-12-09 21:40 UTC, art-alexeyenko commented on local-containers/scripts/up.ps1
> +#set node version
the line that does it is
`$nodeVersion = $xmCloudBuild.renderingHosts.nextjsstarter.nodeVersion`
It is very self explanatory without the comment

2024-12-09 21:50 UTC, addy-pathania commented on local-containers/scripts/up.ps1
> +#set node version
The entire block of code is focused on setting the Node.js version, and the comment provides a clear summary of its purpose. While the code may seem self-explanatory, the comment adds clarity, especially for someone new to the script.

2024-12-09 22:58 UTC, art-alexeyenko commented on local-containers/scripts/up.ps1
> +#set node version
I'd rather us remove it for less noise - or expand with something more substantial. Even someone new to the script should be able to deduce that the below four lines of code set a node version

2024-12-10 08:11 UTC, yavorsk commented on local-containers/.env
> +SITECORE_API_KEY_APP_STARTER=
SITECORE_API_KEY_APP_STARTER is being set by the Init scrip, so we can leave it empty

2024-12-10 08:17 UTC, yavorsk commented on local-containers/scripts/up.ps1
> +#set node version
I noticed that the comment was wrong, so just updated it. My arguments to leave it as it is are:
- the code below it is not just one liner
- this comment feels consistent with the rest comments in the script, so...

2024-12-10 08:20 UTC, yavorsk commented
hey @addy-pathania @art-alexeyenko , I confirm the local containers changes should be good. They consist of some variable and local site renamings, that were discussed during the work, no change to functionality

2024-12-10 14:29 UTC, art-alexeyenko approved these changes

2024-12-10 14:35 UTC, merged